// src/lib/content/schemas.ts
/*
File defines frontmatter model for content in src/content/*. 
Fields like `slug` and `redirectFrom` (previous slugs) are automatically
generated and out of schemas.ts.
Fields `id` automatically fill `from new-entry` and validated separately.
Fields `order` validated separately.
Rule: published content needs `lastReviewed` validated by `rules.ts`. 
*/
import { z } from 'astro/zod';
import {hasReviewDate, reviewDateError } from './rules.ts'

// allowed formats: YYYY | YYYY-MM | YYYY-MM-DD ; always as string
const PARTIAL_DATE = /^\d{4}(-(0[1-9]|1[0-2])(-(0[1-9]|1\d|2\d|3[01]))?)?$/;

// convert date from yaml to string and validate
const partialDate = z.preprocess(
    (d) => {
        if (typeof d === 'number') return String(d);
        if (d instanceof Date && !Number.isNaN(d.getTime())) return d.toISOString().slice(0, 10);
        return d;
    },
    z.string().regex(PARTIAL_DATE, { error: 'expected YYYY, YYYY-MM or YYYY-MM-DD' }),
);

// status for content
const publishedStatus = z.enum([
    'planned',
    'researching',
    'draft',
    'review',
    'published',
    'needs-review',
    'archived',
]);

// global atlas node
export const atlasNodeSchema = z.strictObject({
    targetId: z.string().min(1),
    title: z.string().optional(),
    layer: z.enum(['A0','A1', 'A2', 'A3', 'A4']),
    summary: z.string().min(1),
});

// shared by system, concept and gateway
export const contextFields = z.strictObject({
    id: z.string().min(1).describe('stable id, generated by `new-entry`, do not edit'),
    title: z.string().min(1).describe('title of this content'),
    aliases: z.array(z.string()).default([]).describe('alternative titles'),
    summary: z.string().min(1).describe('short summary of the text'),
    status: publishedStatus.describe('choose from: `planned`, `researching`, `draft`, `review`, `published`, `needs-review`, `archived`'),
    lastReviewed: z.date().optional().describe('needed with status `review`, `published`, `needs-review`, date of last audit, allowed format: `YYYY-MM-DD`'),
})

// shared by sections in different types of contents
export const sectionFields = z.strictObject({
    id: z.string().min(1).describe('stable id, generated by `new-entry`, do not edit'),
    title: z.string().min(1).describe('title of this content'),
    aliases: z.array(z.string()).default([]).describe('alternative titles'),
    summary: z.string().min(1).describe('short summary of the text'),
    learningGoal: z.string().min(1).describe('short description what user will learn from section'),
    status: publishedStatus.describe('choose from: `planned`, `researching`, `draft`, `review`, `published`, `needs-review`, `archived`'),
    order: z.int().min(1).describe('int number, defines order of reading for user'),
});

// shared by articles in different types of contents
export const articleFields = z.strictObject({
    id: z.string().min(1).describe('stable id, generated by `new-entry`, do not edit'),
    title: z.string().min(1).describe('title of this content'),
    aliases: z.array(z.string()).default([]).describe('alternative titles'),
    keywords: z.array(z.string()).default([]).describe(`words related to the content`),
    summary: z.string().min(1).describe('short summary of the text'),
    status: publishedStatus.describe('choose from: `planned`, `researching`, `draft`, `review`, `published`, `needs-review`, `archived`'),
    changeSensitivity: z.enum(['low', 'medium', 'high']).describe('allowed choices: `low`, `medium`, `high`, defines how often content need review'),
    order: z.int().min(1).describe('int number, defines order of reading for user'),
    lastReviewed: z.date().optional().describe('needed with status `review`, `published`, `needs-review`, date of last audit, allowed format: `YYYY-MM-DD`'),
});

// shared in different types of sources
export const sourceFields = z.strictObject({
    id: z.string().min(1).describe('stable id, generated by `new-entry`, do not edit'),
    title: z.string().min(1).describe('title of this content'),
    authors: z.array(z.string()).min(1).describe('author/authors of the source, includes organizations, etc.'),
    published: partialDate.optional().describe('date of publication, allowed formats: YYYY, YYYY-MM, YYYY-MM-DD'),
    url: z.url({ protocol: /^https?$/ }).optional().describe('url of source (if available)'),
    notes: z.string().optional().describe('own notes'),
});

// A2/A3 layer
export const systemSchema = z.strictObject({
    ...contextFields.shape,
    scope: z.string().min(1).describe('defines when starts and ends scope of this content'),
    coverage: z.enum(['planned', 'in-progress', 'core-complete']).describe('choose from: `planned`, `in-progress`, `core-complete`, answers how complete the content is'),
}).refine(hasReviewDate, reviewDateError);

// A0/A1 layer
export const conceptSchema = z.strictObject({
    ...contextFields.shape,
    scope: z.string().optional().describe('optional for coverage: `topic-bucket`, otherwise is needed, defines when starts and ends scope of this content'),
    coverage: z.enum(['topic-bucket', 'planned', 'in-progress', 'core-complete']).describe('choose from: `topic-bucket`, `planned`, `in-progress`, `core-complete`, answers how complete the content is'),
}).refine(
  (c) => c.coverage === 'topic-bucket' || !!c.scope,
  { error: 'concept requires scope unless coverage is "topic-bucket"', path: ['scope'] }
).refine(hasReviewDate, reviewDateError);

// A4 layer
export const gatewaySchema = z.strictObject({
    ...contextFields.shape,
    entryQuestion: z.string().min(1).describe('question this content answers')
}).refine(hasReviewDate, reviewDateError);

// for system and concept sections
export const sectionSchema = z.strictObject({
    ...sectionFields.shape,
    scope: z.string().min(1).describe('defines when starts and ends scope of this content'),
})

// for gateway sections
export const sectionGatewaySchema = z.strictObject({
    ...sectionFields.shape,
    entryQuestion: z.string().min(1).describe('question this content answers')
})

// for system and concept articles
export const articleSchema = z.strictObject({
    ...articleFields.shape,
}).refine(hasReviewDate, reviewDateError);

// for gateway articles
export const articleGatewaySchema = z.strictObject({
    ...articleFields.shape,
    entryQuestion: z.string().min(1).describe('question this content answers')
}).refine(hasReviewDate, reviewDateError);

// common for every types of tools
export const toolSchema = z.strictObject({
    id: z.string().min(1).describe('stable id, generated by `new-entry`, do not edit'),
    title: z.string().min(1).describe('title of this content'),
    summary: z.string().min(1).describe('short summary of the text'),
    status: publishedStatus.describe('choose from: `planned`, `researching`, `draft`, `review`, `published`, `needs-review`, `archived`'),
    learningGoal: z.string().min(1).describe('short description what user will learn from tool'),
    fallbackDescription: z.string().min(1).describe('description the goal, can replace the tool'),
    standalone: z.boolean().describe('boolean value: `false` or `true`, false = embedded in article, true has own route'),
    lastReviewed: z.date().optional().describe('needed with status `review`, `published`, `needs-review`, date of last audit, allowed format: `YYYY-MM-DD`'),
}).refine(hasReviewDate, reviewDateError);

export const standardSourceSchema = z.strictObject({
    ...sourceFields.shape,  
    designation: z.string().min(1).describe('example: `RFC-1034`, `ISO-8601`, `IEEE-802.11`'),
});

export const bookSourceSchema = z.strictObject({
    ...sourceFields.shape,
    isbn: z.string().optional().describe('example: ISBN-10, ISBN-13'),
    publisher: z.string().optional().describe('publisher of this book, not the author/authors'),
    edition: z.string().optional().describe(`version of the book at the moment of use`),
});

export const paperSourceSchema = z.strictObject({
    ...sourceFields.shape,
    doi: z.string().optional().describe('example: `10.<prefix>/<suffix>` without `https://doi.org/`'),
    venue: z.string().optional().describe('name of the journal, conference, or institution, etc., in which the source appeared'),
});

export const reportSourceSchema = z.strictObject({
    ...sourceFields.shape,
    publisher: z.string().optional().describe('publisher of this report, not the author/authors'),
});

export const documentationSourceSchema = z.strictObject({
    ...sourceFields.shape,
    url: z.url({ protocol: /^https?$/ }).describe('url of source'),
    accessedAt: z.date().describe('date the source was accessed, allowed format: `YYYY-MM-DD`'),
    version: z.string().optional().describe(`version of the document at the moment of use`),
});

export const webSourceSchema = z.strictObject({
    ...sourceFields.shape,
    url: z.url({ protocol: /^https?$/ }).describe('url of source'),
    accessedAt: z.date().describe('date the source was accessed, allowed format: `YYYY-MM-DD`'),
});
